title: cFDevOps
description: FPL2020 Workshop on DevOps support for Cloud FPGA platforms
logo: assets/img/logo.png
anchor1_url: program
anchor1_txt: Program
anchor2_url: registration
anchor2_txt: Registration
anchor3_url: contact
anchor3_txt: Contact
kramdown:
  auto_ids: true
sass:
    sass_dir: _sass

